tap "jesseduffield/lazygit"
brew "antigen"
brew "cmake"
brew "node"
brew "atuin"
brew "fd"
brew "fzf"
brew "gh"
brew "git-delta"
brew "git-interactive-rebase-tool"
brew "gnu-sed"
brew "openssl@3"
brew "unbound"
brew "gnutls"
brew "gnupg"
brew "libpq", link: true
brew "neovim", args: ["HEAD"]
brew "pinentry-mac"
brew "xz"
brew "postgresql@15"
brew "pyenv"
brew "python@3.11"
brew "ripgrep"
brew "tmux"
brew "zoxide"
brew "jesseduffield/lazygit/lazygit"
